trigger:
- main

pool: Default

stages: 
- stage: TestServer
  pool: 
    name: TestServer
  jobs:
  - job: KillAnyNodeServer
    steps:
    - script: killAll node

  - job: SetEnvAndRunServer
    steps:
    - script: |
        cd client
        touch env.js
        echo "var user = '$DBUser';" >> env.js
        echo "var password = '$password'" >> env.js
        echo "var host = '$host'" >> env.js
        echo "var port = $port" >> env.js
        echo "var database= '$databaseTEST'" >> env.js
        echo "exports.user = user;" >> env.js
        echo "exports.password = password;" >> env.js
        echo "exports.host = host;" >> env.js
        echo "exports.port = port;" >> env.js
        echo "exports.database = database;" >> env.js
        npm install
        node index &

  - job: RunTestsServer
    steps:
    - script: echo "Tests should be run here"


- stage: TestClient
  dependsOn: TestServer
  pool: 
    name: TestClient
  jobs:
  - job: KillAnyPythonClient
    steps:
    - script: killAll node
  
  - job: RunTestClient
    steps:
    - script: |
        cd flutter-frontend
        flutter build web
        cd build/web
        python3 -m http.server 3000 &
  - job: RunTestsClient
    steps:
    - script: echo "Tests should be run here"
  
  - job: TerminateClient
    steps: 
    - script: killAll node


- stage: TerminateTestServer
  dependsOn: TestClient
  pool: 
    name: TestServer
  jobs:
  - job: KillAnyNodeServer
    steps:
    - script: killAll node

- stage: DeployServer
  dependsOn: TerminateTestServer
  pool:
    name: DeployServer
    jobs:
    - job: KillAnyNodeServer
      steps:
      - script: killAll node
    
    - job: SetEnvAndRunServer
      steps:
      - script: |
          cd client
          touch env.js
          echo "var user = '$DBUser';" >> env.js
          echo "var password = '$password'" >> env.js
          echo "var host = '$host'" >> env.js
          echo "var port = $port" >> env.js
          echo "var database= '$database'" >> env.js
          echo "exports.user = user;" >> env.js
          echo "exports.password = password;" >> env.js
          echo "exports.host = host;" >> env.js
          echo "exports.port = port;" >> env.js
          echo "exports.database = database;" >> env.js


- stage: DeployClient
  dependsOn: TerminateTestServer
  pool: 
    name: DeployClient
  jobs:
  - job: KillAnyPythonClient
    steps:
    - script: killAll python
  
  - job: SetEnvAndRunClient
    steps:
    - script: |
        cd flutter-frontend
        flutter build web
        cd build/web
        python3 -m http.server 3000 &
